
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
#include "UnitTesting.h"
#include "test_suites.h"

TEST_FUNCTION testSomething();

TEST_FUNCTION_ptr _asdf[] = {
    testSomething,
};

const TestSuite asdf = {
    "asdf",
    sizeof(_asdf) / sizeof(TEST_FUNCTION_ptr),
    _asdf
};

const TestSuite* all_suites[TOTAL_SUITES] = {
    &asdf,
};
