
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
#ifndef TEST_SUITES_H
#define TEST_SUITES_H

#include "UnitTesting.h"

extern const TestSuite asdf;

#define TOTAL_SUITES    1

extern const TestSuite* all_suites[TOTAL_SUITES];

#endif // TEST_SUITES_H
