
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
#include "UnitTesting.hpp"
#include "test_suites.hpp"

using namespace ucToolbox::unitTests;

TEST_FUNCTION byteQueueConstructorTest();
TEST_FUNCTION byteQueueTest();
TEST_FUNCTION byteQueueStressTest();

const TEST_FUNCTION_ptr _QueueTests[] = {
    byteQueueConstructorTest,
    byteQueueTest,
    byteQueueStressTest,
};

const TestSuite QueueTests = {
    "QueueTests",
    sizeof(_QueueTests) / sizeof(TEST_FUNCTION_ptr),
    _QueueTests
};

const ucToolbox::unitTests::TestSuite all_suites[TOTAL_SUITES] = {
    QueueTests,
};
