
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
#include "UnitTesting.hpp"
#include "test_suites.hpp"

TEST_FUNCTION byteQueueTest();

const TEST_FUNCTION_ptr _tests/QueueTests[] = {
    byteQueueTest,
};

const TestSuite tests/QueueTests = {
    "tests/QueueTests",
    sizeof(_tests/QueueTests) / sizeof(TEST_FUNCTION_ptr),
    _tests/QueueTests
};

const TestSuite all_suites[TOTAL_SUITES] = {
    tests/QueueTests,
};
