
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
#ifndef TEST_SUITES_HPP
#define TEST_SUITES_HPP

#include "UnitTesting.hpp"


#define TOTAL_SUITES    0

extern const TestSuite all_suites[TOTAL_SUITES];

#endif // TEST_SUITES_HPP
