
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
#ifndef TEST_SUITES_HPP
#define TEST_SUITES_HPP

#include "UnitTesting.hpp"

extern const ucToolbox::unitTests::TestSuite QueueTests;

#define TOTAL_SUITES    1

extern const ucToolbox::unitTests::TestSuite all_suites[TOTAL_SUITES];

#endif // TEST_SUITES_HPP
