import os, re

SOURCE_FILE_EXTS = [".c", ".cpp"]
HEADER_FILE_EXTS = [".h", ".hpp"]

OUTPUT_SOURCE_FILE = "test_suites.cpp"
OUTPUT_HEADER_FILE = "test_suites.hpp"

UNIT_TEST_SOURCE_FILE = "UnitTesting.cpp"
UNIT_TEST_HEADER_FILE = "UnitTesting.hpp"

EXCLUDE_FILES = [
    UNIT_TEST_SOURCE_FILE,
    UNIT_TEST_HEADER_FILE,
    OUTPUT_SOURCE_FILE,
    OUTPUT_HEADER_FILE,
    "main.cpp"
]

GEN_FILE_HEADER_TEXT = """
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
"""

def main():
    sources, headers = getSourceAndHeaderFiles('.')
    generateOutputSource(sources)
    generateOutputHeader(sources)
        
def generateOutputSource(sources):
    ofile = open(OUTPUT_SOURCE_FILE,"w")
    ofile.write(GEN_FILE_HEADER_TEXT)
    ofile.write("#include \"" + UNIT_TEST_HEADER_FILE + "\"\n")
    ofile.write("#include \"" + OUTPUT_HEADER_FILE + "\"\n\n")
    
    test_functions = getAllTestFunctionsInSourceList(sources)
    ofile.write(genTestFuncDeclarations(test_functions))
    ofile.write("\n")
    
    for source_file in sources:
        ofile.write(genTestSuite(source_file))
        
    ofile.write(getAllTestSuitesStruct(sources))
    ofile.close()
    
def generateOutputHeader(sources):
    ofile = open(OUTPUT_HEADER_FILE,"w")
    ofile.write(GEN_FILE_HEADER_TEXT)
    header_guard_name = OUTPUT_HEADER_FILE.replace('.','_').upper()
    ofile.write("#ifndef " + header_guard_name + "\n")
    ofile.write("#define " + header_guard_name + "\n\n")
    
    ofile.write("#include \"" + UNIT_TEST_HEADER_FILE + "\"\n\n")
    
    for source in sources:
        ofile.write("extern const TestSuite " + genTestSuiteName(source) + ";\n")
    ofile.write("\n")
    
    num_suites = len(sources)
    ofile.write("#define TOTAL_SUITES    " + str(num_suites) + "\n\n")
    ofile.write("extern const TestSuite all_suites[TOTAL_SUITES];\n\n")
    
    ofile.write("#endif // " + header_guard_name + "\n")
    ofile.close()
    
def getAllTestFunctionsInSourceList(source_file_list):
    test_functions = []
    for file in source_file_list:
        test_functions.extend(getTestFunctionsFromFile(file))
    return test_functions

def genTestFuncDeclarations(test_functions):
    output = ""
    for function in test_functions:
        output += "TEST_FUNCTION " + function + "();\n"
    return output

def genTestSuite(source_file):
    suite_name = genTestSuiteName(source_file)
    test_functions = getTestFunctionsFromFile(source_file)
    
    output = "const TEST_FUNCTION_ptr _" + suite_name + "[] = {\n"
    
    for function in test_functions:
        output += "    " + function + ",\n"
    output += "};\n\n"
    
    output += "const TestSuite " + suite_name + " = {\n"
    output += '    "' + suite_name + '",\n'
    output += "    sizeof(_" + suite_name + ") / sizeof(TEST_FUNCTION_ptr),\n"
    output += "    _" + suite_name + "\n"
    output += "};\n\n"
    
    return output

def getAllTestSuitesStruct(source_files):
    num_suites = len(source_files)
    output = "const TestSuite all_suites[TOTAL_SUITES] = {\n"
    
    for file in source_files:
        output += "    " + genTestSuiteName(file) + ",\n"
        
    output += "};\n"
    return output

def genTestSuiteName(source_file):
    return source_file.split('.')[0]

def getTestFunctionsFromFile(path):
    function_pattern = re.compile(r'TEST_FUNCTION\s+.+\s*\(')
    infile = open(path)
    intext = infile.read()
    infile.close()
    raw_function_list = re.findall(function_pattern, intext)
    clean_function_list = []
    for function in raw_function_list:
        function = function.replace('TEST_FUNCTION','')
        function = function.replace('(','')
        function = function.replace('\n','').replace('\r','')
        function = function.strip()
        clean_function_list.append(function)
    return clean_function_list
    
def getSourceAndHeaderFiles(path):
    sources = []
    headers = []
    for item in os.listdir(path):
        if item in EXCLUDE_FILES:
            continue
        if isSourceFile(item):
            sources.append(item)
        elif isHeaderFile(path):
            headers.append(path)
    return sources, headers
            
def isSourceFile(path):
    if os.path.isfile(path):
        for ext in SOURCE_FILE_EXTS:
            if path.endswith(ext):
                return True
    return False

def isHeaderFile(path):
    if os.path.isfile(path):
        for ext in HEADER_FILE_EXTS:
            if path.endswith(ext):
                return True
    return False

if __name__ == "__main__":
    main()