
/*
Generated by TestSuiteGenerator.py. Don't edit this file manually.
*/
#include "UnitTesting.hpp"
#include "test_suites.hpp"

using namespace ucToolbox::unitTests;

TEST_FUNCTION byteQueueConstructorTest();
TEST_FUNCTION byteQueueTest();
TEST_FUNCTION byteQueueStressTest();
TEST_FUNCTION streamTest();
TEST_FUNCTION parserTestTest();

const TEST_FUNCTION_ptr _QueueTests[] = {
    byteQueueConstructorTest,
    byteQueueTest,
    byteQueueStressTest,
};

const TestSuite QueueTests = {
    "QueueTests",
    sizeof(_QueueTests) / sizeof(TEST_FUNCTION_ptr),
    _QueueTests
};

const TEST_FUNCTION_ptr _StreamTests[] = {
    streamTest,
};

const TestSuite StreamTests = {
    "StreamTests",
    sizeof(_StreamTests) / sizeof(TEST_FUNCTION_ptr),
    _StreamTests
};

const TEST_FUNCTION_ptr _ParserTests[] = {
    parserTestTest,
};

const TestSuite ParserTests = {
    "ParserTests",
    sizeof(_ParserTests) / sizeof(TEST_FUNCTION_ptr),
    _ParserTests
};

const ucToolbox::unitTests::TestSuite all_suites[TOTAL_SUITES] = {
    QueueTests,
    StreamTests,
    ParserTests,
};
